- name: Installer NGINX et RTMP module
  apt:
    name:
      - nginx
      - libnginx-mod-rtmp
      - ffmpeg
    update_cache: yes

- name: Créer Dossier Stream
  file:
    path: "/var/www/html/stream/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - hls
    - dash

- name: Copier main.html
  copy:
    src: index.html
    dest: /var/www/html/
    mode: '0644'

- name: Copier nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Copier streamer site config
  copy:
    src: streamer
    dest: /etc/nginx/sites-enabled/streamer
    mode: '0644'

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
